name: cspeedtest
base: core18
version: '1.5.2'
summary: Measure network throughput between a server and any terminal
description: |
  Client-less network speed test for GNU/Linux servers, using GNU libncurses
  to estimate network throughput between your server and wherever you are
  connecting from. Works on any client platform that has a terminal that supports
  curses (e.g. iOS, Android, Mac OS, Windows, Linux, etc).
grade: stable
confinement: strict

parts:
  curses-speedtest:
    source: https://github.com/jonbirge/curses-speedtest.git
    plugin: autotools
    build-packages:
      - libncurses5-dev
    stage-packages:
      - libncurses5

apps:
  cspeedtest:
    command: bin/cspeedtest
    