name: cspeedtest
base: core18
version: '1.5.1'
summary: Terminal-based network speed test for GNU/Linux servers.
description: |
  Client-less network speed test for GNU/Linux servers, using curses and your
  terminal to estimate network path speed between you and your server.
grade: stable
confinement: strict
website: https://cspeedtest.birge.us

parts:
  curses-speedtest:
    source: https://github.com/jonbirge/curses-speedtest.git
    plugin: autotools
    build-packages:
      - libncurses-dev
    stage-packages:
      - libncurses-dev

apps:
  cspeedtest:
    command: bin/cspeedtest
    