name: cspeedtest
base: core18
version: '1.5.5'
summary: Measure network throughput between a server and any terminal
#website: https://cspeedtest.birge.us/
#contact: https://cspeedtest.birge.us/contact
#source-code: https://github.com/jonbirge/curses-speedtest
#issues: [https://github.com/jonbirge/curses-speedtest/issues]
description: |
  Client-less network speed test for GNU/Linux servers, using GNU libncurses
  to estimate network throughput between your server and wherever you are
  connecting from. Automatically work on any client platform that has a
  terminal that supports curses (e.g. iOS, Android, Mac, Windows, Linux, etc).
license: GPL-3.0
grade: stable
confinement: strict

parts:
  curses-speedtest:
    source: https://github.com/jonbirge/curses-speedtest.git
    plugin: autotools
    build-packages:
      - libncurses5-dev
    stage-packages:
      - libncurses5

apps:
  cspeedtest:
    command: bin/cspeedtest
