name: cspeedtest
base: core22
version: 1.9.3
summary: Measure network throughput between a server and your terminal using curses
website: https://cspeedtest.birge.us/
contact: https://cspeedtest.birge.us/contact
source-code: https://github.com/jonbirge/cspeedtest
issues: https://github.com/jonbirge/cspeedtest/issues
description: |
  Clientless network speed test for GNU/Linux servers, using ncurses
  to estimate network throughput between your server and wherever you are
  connecting from. Automatically works on any client platform that has a
  terminal that supports curses (e.g. iOS, Android, Mac, Windows, Linux, etc).
license: GPL-3.0
grade: devel
confinement: devmode

parts:
  cspeedtest:
    source: .
    plugin: autotools
    build-packages:
      - libncurses5-dev
    stage-packages:
      - libncurses5

apps:
  cspeedtest:
    command: usr/local/bin/cspeedtest

